version: "3.7"

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    volumes:
      - "./pgsql:/var/lib/pgsql"
        
  api:
    image: node
    working_dir: /app
    container_name: node
    restart: always
    volumes:
      - "./:/app"
    command:
      - sh
      - -c
      - |
        npm install
        npm run start:dev
    ports: 
      - "3000:3000"
    depends_on:
      - db
                
                